# action.yml
name: 'GitHub Organization Activity Report'
description: 'Create a daily commit activity report for a GitHub organization'
author: 'Daniel Benesch'
inputs:
  token:
    description: 'GitHub access token for the organization (needs repo and read:org permissions)'
    required: true
  organization:
    description: 'The organization to create the report for'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'gray-dark'