name: 'Github Organization Activity Report'
description: 'Create a daily user activity report for a Github organization'
author: 'Daniel Benesch'
inputs:
  token:
    description: 'GitHub access token for the organization'
    required: true
  organization:
    description: 'The organization to create the report for'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'gray-dark'